apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendtotable
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: ''
  - name: accountKey
    value: ''
  - name: tableName
    value: ''